name: unidb
suffix: ~  # add suffix to saved images
model: denoising
distortion: derain
gpu_ids: [0]

sde:
  lambda_square: 30
  T: 100

  solver_step: 20 # steps for unidb-solver: 5, 10, 20, 25, 50, 100
  method: euler # method for solver: euler, noise-solver-1, noise-solver-2, data-solver-1, data-solver-2
  solver_type: sde # sde/mean-ode
  schedule: cosine # linear, cosine
  eps: 0.005
  gamma: !!float 1e7 # 1e6, 1e7, 1e8
  
degradation:
  # for super-resolution
  scale: 4

datasets:
  test1:
    name: Val_Dataset
    mode: LQGT
    dataroot_GT: ~
    dataroot_LQ: ~

#### network structures
network_G:
  which_model_G: ConditionalUNet
  setting:
    in_nc: 3
    out_nc: 3
    nf: 64
    depth: 4

#### path
path:
  pretrain_model_G: ~
