name: unidb
suffix: ~  # add suffix to saved images
model: denoising
distortion: inpaint
gpu_ids: [0]

sde:
  lambda_square: 30
  T: 100

  solver_step: 20 # steps for unidb-solver
  method: euler # method for solver: euler, noise-solver-1, noise-solver-2, data-solver-1, data-solver-2...
  solver_type: sde # sde/mean-ode/pf-ode
  schedule: cosine # linear, cosine
  eps: 0.005
  gamma: !!float 1e7
  
degradation:
  # for super-resolution
  scale: 4

  # for inpainting
  mask_root: ~

datasets:
  test1:
    name: Val_Dataset
    mode: GT
    dataroot_GT: ~

#### network structures
network_G:
  which_model_G: ConditionalUNet
  setting:
    in_nc: 3
    out_nc: 3
    nf: 64
    depth: 4

#### path
path:
  pretrain_model_G: ~
